site_name: PULSAR HRI Documentation
site_url: https://github.com/PulsarHRI/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange

  font:
    text: Montserrat medium
    code: Red Hat Mono
  # icon:
  #     logo: material/robot
  logo: assets/icons/P_Logo_white_svg.png
  favicon: assets/icons/icon.ico
  features:
    - navigation.footer
    - toggle
    - search.highlight
    - content.code.copy
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pulsarhri
    - icon: material/home
      link: https://pulsarhri.com

nav:
  - index.md
  - why_pulsar.md
  - How to Use PULSAR HRI Hardware: 
      - mechanical_interfaces.md
      - electrical_interfaces.md
      - led.md
      - gui.md
      - "Python API":
          - python_api/install_python_api.md
          - python_api/cli.md
          - Example scripts:
            - python_api/example_single_actuator.md
            - python_api/example_several_actuators.md
            - python_api/example_advanced_features.md
            - python_api/example_log_to_csv.md
          - Code Documentation:
            - python_api/class_PulsarActuator.md
            - python_api/class_PCP_over_USB.md
  - How to Use AUGUR Digital Twin:
    - digital_twin\pulsar-digital-twin-context.md
    - digital_twin\how-to-install-digital-twin.md
    - Examples:
      - digital_twin\example_overview.md
      - digital_twin\download.md
      - digital_twin\example_mujoco-integration-arm.md
      - digital_twin\example_mujoco-integration-pendulum.md
      - digital_twin\example_raw-telemetry-plotting.md
  - Control Modes Explained:
      - control/00-control-modes-overview.md
      - control/01-control-modes-parameters.md
  - support.md
  - faq.md


copyright: Copyright &copy; 2025 PULSAR HRI
