site_name: PULSAR HRI Documentation
site_url: https://github.com/PulsarHRI/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange

  font:
    text: Montserrat medium
    code: Red Hat Mono
  # icon:
  #     logo: material/robot
  logo: assets/icons/P_Logo_white_svg.png
  favicon: assets/icons/icon.ico
  features:
    - navigation.footer
    - toggle
    - search.highlight
    - content.code.copy
plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pulsarhri
    # - icon: material/home
    #   link: https://pulsarhri.com

nav:
  - index.md
  - why_pulsar.md
  - How to Use PULSAR HRI Hardware: 
      - mechanical_connection.md
      - electrical_connection.md
      - gui.md
      - "Python API":
          - install_python_api.md
          - cli.md
          - Example scripts:
            - example_scripts/examples-overview.md
            - example_scripts/single-actuator.md
            - example_scripts/several-actuators.md
            - example_scripts/changing-parameters.md
            - example_scripts/log-to-csv.md
          - Actuator Class:
            - 04-functions-explained/00-functions-overview.md
            - 04-functions-explained/01-actuator-parameters-explained.md
            - 04-functions-explained/02-pcp-api-functions.md
            - 04-functions-explained/03-DT-functions.md
  - How to Use AUGUR Digital Twin:
      - 02-how-to-simulate-actuators-with-digital-twin/00-DT-pulsar-digital-twin-context.md
      - 02-how-to-simulate-actuators-with-digital-twin/01-DT-how-to-install-digital-twin.md
      - "Actuator Digital Twin simulation examples":
          - 02-how-to-simulate-actuators-with-digital-twin/02-actuator-digital-twin-examples/00-DT-examples-overview.md
          - 02-how-to-simulate-actuators-with-digital-twin/02-actuator-digital-twin-examples/01-DT-raw-telemetry-plotting.md
          - 02-how-to-simulate-actuators-with-digital-twin/02-actuator-digital-twin-examples/02-DT-mujoco-integration-pendulum.md
          - 02-how-to-simulate-actuators-with-digital-twin/02-actuator-digital-twin-examples/03-DT-mujoco-integration-arm.md
  
  - Control Modes Explained:
      - 03-actuator-control-modes-explained/00-control-modes-overview.md
      - 03-actuator-control-modes-explained/01-control-modes-parameters.md

  # This is already in How to Use AUGUR Digital Twin
  # - Download AUGUR Digital Twin:
  #     - 05-actuator-digital-twin-download/00-DT-download.md
  - Licensing & Support:
      - licensing.md
      - support.md
  - faq.md

# unused documents were renamed to .txt so they will not appear in searches
#  - Classes Definitions:
#      - "Introduction": classes.md
#      - "Initialization and Constructor": classes-01-InitialisationContrustor.md
#      - "Connection and Adress Management": Classes-02-ConnectionAndAdress.md
#      - "Feedback Configuration from Pulsar Actuator": Classes-03-Feedback.md
#      - "Pulsar Actuator Parameters": Classes-04-PulsarActuator_Parameters.md
#      - "Predefined Performance Profiles": Classes-05-PerformanceProfiles.md
#      - "Actuator Operation: Startup, Shutdown, and Control Modes": Classes-06-ActuatorOperation.md

copyright: Copyright &copy; 2025 PULSAR HRI
