site_name: Pulsar API Documentation
site_url: https://github.com/PulsarHRI/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange

  font:
    text: Montserrat medium
    code: Red Hat Mono
  # icon:
  #     logo: material/robot
  logo: assets/P_Logo_white_svg.png
  favicon: assets/icon.ico
  features:
    - navigation.footer

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pulsarhri
    # - icon: material/home
    #   link: https://pulsarhri.com

nav:
  - Home: index.md
  - Examples:
      - "Controlling One Target": 01-Single-Actuator.md
      - "Controlling Two Targets": 02_Two-Actuators.md
      - "Changing Actuator Parameters": 03-Changing-Parameters.md 
      - "Logging data and saving in .csv File": 04-Log-To-CSV.md
  - Classes Definitions: classes.md


copyright: Copyright &copy; 2025 Pulsar
