site_name: PULSAR HRI Ecosystem Documentation
site_description: How to use PULSAR HRI hardware and software, including actuators APIs and AUGUR digital twin.

site_url: https://pulsarhri.github.io/
use_directory_urls: true

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange

  font:
    text: Montserrat medium
    code: Red Hat Mono
  # icon:
  #     logo: material/robot
  logo: assets/icons/P_Logo_white_svg.png
  favicon: assets/icons/icon.ico
  features:
    - navigation.footer
    - toggle
    - search.highlight
    - content.code.copy
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pulsarhri
    # - icon: material/home
    #   link: https://pulsarhri.com

nav:
  - index.md
  - Quickstart Tutorials: 
    - "Set up Real Actuator and connect via USB": quickstarts/quickstart_set_up_usb.md
    - "No-Code Desktop App for Real Actuator": quickstarts/quickstart_desktop_app.md
    - "Python API for Real Actuator": quickstarts/quickstart_python_api.md
  - "Set Up & Communication": 
    - "with Real Actuators":
      - set_up/set_up_real.md
      - communicate/communicate_real.md
      - "More Details on Hardware Interfaces":
        - set_up/hardware_interfaces/mechanical_interfaces.md
        - set_up/hardware_interfaces/electrical_interfaces.md
        - set_up/hardware_interfaces/led.md
    - "with Virtual Actuators":
      - set_up/set_up_virtual.md
      - communicate/communicate_virtual.md
  - "Control Actuators":
    - "Desktop App": control/desktop_app/desktop_app.md
    - "Python API":
        - control/python_api/install_python_api.md
        - control/python_api/cli.md
        - Example scripts:
          - control/python_api/example_single_actuator.md
          - control/python_api/example_several_actuators.md
          - control/python_api/example_advanced_features.md
          - control/python_api/example_log_to_csv.md
        - API Code Reference:
          - control/python_api/class_PulsarActuator.md
          - control/python_api/class_PCP_over_USB.md
    - Control Modes Explained:
      - control/control_modes_explained/control_modes_overview.md
      - control/control_modes_explained/control_modes_parameters.md


  # This is already in How to Use AUGUR Digital Twin
  # - Download AUGUR Digital Twin:
  #     - 05-actuator-digital-twin-download/00-DT-download.md
  # - Licensing & Support:
  #     - licensing.md
  - Downloads:
      - download/download_app.md
      - download/download_dtwin.md
  - support.md
  - faq.md

# unused documents were renamed to .txt so they will not appear in searches
#  - Classes Definitions:
#      - "Introduction": classes.md
#      - "Initialization and Constructor": classes-01-InitialisationContrustor.md
#      - "Connection and Adress Management": Classes-02-ConnectionAndAdress.md
#      - "Feedback Configuration from Pulsar Actuator": Classes-03-Feedback.md
#      - "Pulsar Actuator Parameters": Classes-04-PulsarActuator_Parameters.md
#      - "Predefined Performance Profiles": Classes-05-PerformanceProfiles.md
#      - "Actuator Operation: Startup, Shutdown, and Control Modes": Classes-06-ActuatorOperation.md

copyright: Copyright &copy; 2025 PULSAR HRI
