site_name: Pulsar API Documentation
site_url: https://github.com/PulsarHRI/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: grey
      accent: deep orange

  font:
    text: Montserrat medium
    code: Red Hat Mono
  # icon:
  #     logo: material/robot
  logo: assets/P_Logo_white_svg.png
  favicon: assets/icon.ico
  features:
    - navigation.footer
    - toggle
    - search.highlight
    - content.code.copy
plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pulsarhri
    # - icon: material/home
    #   link: https://pulsarhri.com

nav:
  - 00-home.md
  - How to control hardware actuators: 
      - 00-R-pulsar-hardware-context.md
      - 01-R-how-to-install-hardware.md
      - "Actuator control examples":
          - 00-R-examples-overview.md
          - 01-R-single-actuator.md
          - 02-R-two-actuators.md
          - 03-R-changing-parameters.md
          - 04-R-log-to-csv.md
  - How to simulate actuators with Digital Twin:
      - 00-DT-pulsar-digital-twin-context.md
      - 01-DT-how-to-install-digital-twin.md
      - "Actuator Digital Twin simulation examples":
          - 00-DT-examples-overview.md
          - 01-DT-raw-telemetry-plotting.md
          - 02-DT-mujoco-integration-pendulum.md
          - 03-DT-mujoco-integration-arm.md
  - Actuator control modes explained:
      - 00-control-modes-overview.md
      - 01-control-modes-parameters.md
  - 00-actuator-parameters-explained.md
  - Functions explained:
      - 00-functions-overview.md
      - 01-pcp-api-functions.md
      - 02-DT-functions.md
  - Actuator Digital Twin download:
      - 00-DT-download.md
  - Licensing & Support:
      - 00-licensing.md
      - 01-support.md

#  - Classes Definitions:
#      - "Introduction": classes.md
#      - "Initialization and Constructor": classes-01-InitialisationContrustor.md
#      - "Connection and Adress Management": Classes-02-ConnectionAndAdress.md
#      - "Feedback Configuration from Pulsar Actuator": Classes-03-Feedback.md
#      - "Pulsar Actuator Parameters": Classes-04-PulsarActuator_Parameters.md
#      - "Predefined Performance Profiles": Classes-05-PerformanceProfiles.md
#      - "Actuator Operation: Startup, Shutdown, and Control Modes": Classes-06-ActuatorOperation.md

copyright: Copyright &copy; 2025 Pulsar
