name: Request support
description: File to request support from Pulsar HRI.
title: "[Provide a title]"
assignees:
  - Pulsar HRI
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: request_type
    attributes:
      label: What do you need?
      multiple: true
      options:
        - Help
        - Bug
        - Additional feature request
        - Other
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you need!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Provide the tag/commit id of the version you are using. 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
