import logging
from enum import Enum
from math import nan
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Union

def command_params(args): ...

def command_blink(args): ...

def command_home(args): ...

def command_scan(args): ...

def main(): ...
